cidr_for_vpc          = "10.10.0.0/24"
vpc_name              = "vpc-01"
web_server_name       = "web_server"
instance_types        = "t2.micro"
key_name              = "awskey01"
bastion_instance_name = "bastion_host"
images                = "ami-008b85aa3ff5c1b02"