cidr_for_vpc          = "10.10.0.0/24"
vpc_name              = "vpc-01"
web_server_name       = "web_server"
instance_types        = "t2.micro"
images                = "ami-026ebd4cfe2c043b2"
key_name              = "awskey5"
bastion_instance_name = "bastion_host"