on:
    workflow_dispatch:

jobs:
    packagev2:
        name: packagev2
        runs-on: ubuntu-latest
    
        steps:

        - name: checkout
          uses: actions/checkout@master
          with:
            repository: rahuls512/java-db-Login

        - name: Setup JDK 8
          uses: actions/setup-java@v3
          with:
            distribution: 'temurin'
            java-version: '8'
        
        - name: build package
          run: mvn clean package
        
        - name: create dir
          run: mkdir package && cp target/*.war package
        
        - uses: actions/upload-artifact@v3
          with:
            name: my-artifact
            path: package
        
        - run: ls package

    deploy-package:
          name: deploy-to-s3
          runs-on: ubuntu-latest
          needs: packagev2
          env:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
            aws-region: ap-south-1
          steps: 
            - name: download artifact
              uses: actions/download-artifact@v3
              with:
                name: my-artifact
                path: package
            
            - run: ls -R
                
            - name: deploy package
              run: aws s3 cp package/*.war s3://rsinfotech-application-artifactstore