name: Provision and build an ami

on:
    # push:
      # paths:
      #   - .github/workflows/build.yml
      #   - ../image-builder
      # branches: [main]
    workflow_dispatch:  
jobs:
    provision-packer:
        runs-on: ubuntu-latest
        env:
            AWS_ACCESS_KEY_ID: ${{ secrets.aws_access_key }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.aws_secret_key }}

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: setup the Packer
              id: setup
              uses: hashicorp/setup-packer@main
                
            - name: initialize packer
              id: initpacker
              run: "packer init ./image-builder/"

            - name: fmt packer
              id: fmtpacker
              run: "packer fmt ./image-builder/"
                
            - name: validate packer
              id: validate
              run: "packer validate ./image-builder/"

            - name: build image
              id: build
              run: "packer build ./image-builder/"