on:
    workflow_dispatch:
jobs:
    config-tomcat:
        runs-on: ubuntu-latest
        env:
           ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
           SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
        steps:
            - name: Checkout
              uses: actions/checkout@v2
              
            - name: Configure SSH and Git
              run: |
                mkdir -p ~/.ssh
                echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
                chmod 600 ~/.ssh/id_rsa
                eval "$(ssh-agent)"
                ssh-add ~/.ssh/id_rsa
            - name: configure dynamic inventory
              run: |
                ansible-galaxy collection install amazon.aws
                ansible-inventory -i aws_ec2.yml --list

            - name: configure tomcat
              run: |
                ansible-playbook app_server.yml -i aws_ec2.yml -vvv